# languages.py
LANGUAGES = {
    "Afrikaans": "af-ZA",
    "Albanian": "sq-AL",
    "Arabic": "ar-SA",
    "Bengali": "bn-IN",
    "Chinese (Simplified)": "zh-CN",
    "Chinese (Traditional)": "zh-TW",
    "Czech": "cs-CZ",
    "Danish": "da-DK",
    "Dutch": "nl-NL",
    "English": "en-GB",
    "French": "fr-FR",
    "German": "de-DE",
    "Greek": "el-GR",
    "Hindi": "hi-IN",
    "Hungarian": "hu-HU",
    "Indonesian": "id-ID",
    "Italian": "it-IT",
    "Japanese": "ja-JP",
    "Korean": "ko-KR",
    "Persian": "fa-IR",
    "Polish": "pl-PL",
    "Portuguese": "pt-PT",
    "Punjabi": "pa-IN",
    "Romanian": "ro-RO",
    "Russian": "ru-RU",
    "Spanish": "es-ES",
    "Swedish": "sv-SE",
    "Tamil": "ta-IN",
    "Telugu": "te-IN",
    "Thai": "th-TH",
    "Turkish": "tr-TR",
    "Urdu": "ur-PK",
    "Vietnamese": "vi-VN",
}